apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: MQ-Validation
  owner: MQ-Validation
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/MQ-Validation/multi-tenancy-gitops-apps.git
