apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: instana-agent
  namespace: instana-agent
spec:
  encryptedData:
    key: AgAvDFIgnVZo0CWaJ88r0JPQR11mUVhgWPRzAY7XOyEITeHnGuE+Ptx+g9SNWXeKJamUk8YLKvqUthRpOXgeZbHXCn9VFUEWoP84ePNhEaIfpyHtUCERq1JHqrW+BqlXeEBhT+pWAfyJAQB0h6F5Rr4viaN5BNZIb4lzNrKG2GN0pE5xiUlTqa/STc+NM4dMvYgUOhfmvVHm0G2bUdsczC88o8EpZBJS70r47OxGtWIwPLEKBJK2drpFWHemWIhIXJxnJCrHlNr7SyckeaRVP7NNbVTuEYhqPis211iIg62Eb6MF0SGhndeYz1XitEUmkibJ7g+7AEnIgAhe26/YrtZqTjt4BMeCrXYGgtaVAx8LOoLRbJiU3/C73YQm11el7Bz1wjb5CHJqgZ9knLvfZETZkMF+S75A2haNLdYA+8EW9hNM8YnqOHrRAtqwb/vQlRFOYDLqNnxGamrAqvt9As31ULVoobZjmH/2ftxEbIPC8nfMXvnDw7YWnQO4A4L6zhsG+blnJjv5ysfghYEObaVg5KAv4Gzr5oK8c2uI30hM4spznKSbq0PrmhsQKR1HpdC9h3TFSmgyiYxneLhSuAZ2z8cb4g1uRkBVOqMXVT3cfhzGk6qmw85+6zB1uVScOaR+K9UHp9ravoDXaEiS+sW3Yb1WD0tTbK3Di9rOUaU2AqtzqkWTam7AkL5YXRkKmwDdlryKfUxhs8qvn/jVhytHWwjKg1Uu
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: instana-agent
      namespace: instana-agent

